### ISSUE TITLE
Reorder tasks based on priority

### ISSUE THREAD

**Issue by asakura42** [drvog/yat-rs#1]
Hello! First of all very nice program, thank you. What do you think about automatically reordering of tasks based on their priority?

**Comment by lewis-weinberger** [comment]
Hi @asakura42, sorry it's been a while since I've hacked on `yat`. I've added some functionality to help with sorting tasks based on priority in ba213cd. 

```rs
impl ToDo {
    /// Reorder subtasks based on priority
    pub fn sort_by_priority(&mut self) {
        self.sub_tasks.sort_by(|a, b| {
            // Reverse order so we treat None properly
            b.borrow().priority.cmp(&a.borrow().priority)
        });
    }
}
```

I've introduced a new key-binding for this, by default set to `r`. Hope that helps!

**Comment by asakura42** [comment]
Thank you @lewis-weinberger. It's sad that you rarely develop this project, the idea of nested tasks sounds and looks very cool.
