### ISSUE TITLE
Core dumped when I try to input Unicode character

### ISSUE THREAD

**Issue by asakura42** [drvog/yat-rs#2]
ASCII symbols are okay but when I try to add a task with Unicode symbols (japanese, cyrillic, polish symbols - all), program breaks.

**Comment by lewis-weinberger** [comment]
Hi @asakura42, good spot! I hadn't originally intended to use any non-ASCII characters in my todos, so some of my assumptions in `yat` breakdown when you try to input multi-byte UTF8 characters. 

In particular there were two problems:

1. many `String` methods mix byte-representation and character-representation in their arguments, for example: `insert(&mut self, idx: usize, ch: char)` takes a byte-position and a `char` to insert.
2. some wide characters are displayed over more than one "cell" in the terminal (see [Halfwidth and fullwidth forms](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms)). 

Under my ASCII assumptions these issues weren't a problem, as the byte positions were always character boundaries and characters always fit into one cell. However when you tried multi-byte characters, we had problems!

I believe I have fixed this in ef17e60. I've tested it by inserting characters like `αβγδεζηθ`  and `ぁあぃいぅうぇえ`. If you come across any further crashes or unexpected behavior, please raise another issue.
